# ---------------------------
# Browser & Execution
# ---------------------------
browser = chrome
headless = false
implicit.wait = 30
explicit.wait = 100
base.url = https://mb.io/en-AE
env = qa
extent.report.path = ./reports/MBIO Automation Test Execution Report.html
desktop.width = 1920
desktop.height = 1080

mobile.width = 430
mobile.height = 932
retry.count = 1
